import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CursorProvider from "@/context/cursor-context";
import Cursor from "@/components/cursor";
import TrailImages from "@/components/trail";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TrailImages />
        <CursorProvider>
          {children}
          {/* <Cursor>
            {children}
            </Cursor> */}
        </CursorProvider>
      </body>
    </html>
  );
}
